name: Build Check
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  example:
    runs-on: [ubuntu-latest, macos-latest, macos-13, windows-latest]
    steps:
    - name: Setup bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
    - name: Run 
      run: |
        bazel build //:engine
        bazel build //:release
